---
title: 'Class 6: R functions'
author: "Chenlu Bao"
date: "April 19, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Today we will focus on **R functions** but we will start with a bit of **file reading**.

```{r}
plot(1:10, type = "l", col = "blue")
```

```{r}
read.table("test1.txt", header = TRUE, sep = ",")
```

I am going to see if I can open the other example files by setting the appropriate arguments to the functions.

```{r}
read.table("test2.txt", header = TRUE, sep = "$")
```

```{r}
read.table("test3.txt")
```

```{r}
read.csv("https://bioboot.github.io/bggn213_S18/class-material/test1.txt")
```

## Our first function
Add some numbers
```{r}
add <- function(x, y=1) {
 # Sum the input x and y; the body
 x + y
}
```

```{r}
add(4)
```

```{r}
add(4, 5)
```

```{r}
add(x=4, y=5)
```

```{r}
add( c(1, 3, 5), 1)
```

```{r}
#add(1, 3, 5)
```

```{r}
#add(x=1, y="barry")
```

## Our 2nf emample function

```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
rescale( c(1, 3, NA, 5, 10))
```

```{r}
x <- c(1, 3, NA, 5, 10)
rng <-range(x, na.rm = TRUE)
rng
(x - rng[1]) / (rng[2] - rng[1])

```

```{r}
rescale2 <- function(x, na.rm = TRUE) {
 rng <-range(x, na.rm = na.rm)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2( c(1, 3, NA, 5, 10))
```

```{r}
#rescale2( c(1, 3, "barry"))
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3(1:10)
```

```{r}
rescale3(1:10, plot = TRUE)
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
 print("is it me you are looking for?")
 if(plot) {
   plot(answer, typ="b", lwd=4)
 }
 
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3(1:10, plot = TRUE)
```



